Repository lucasmedeiros/game-slot, pull requests merged in 2021-09, with the labels that each got.

#74 Adiciona Radium ao projeto
  game-slot/frontend/package.json
  game-slot/frontend/src/App.tsx
  game-slot/frontend/src/layout/default/Header/index.tsx
  game-slot/frontend/src/layout/default/Header/styles.ts
  game-slot/frontend/src/styles/index.ts
  game-slot/frontend/src/styles/theme.ts
  game-slot/frontend/yarn.lock
  package.json
  yarn.lock
Labels: refact, rewriting

#78 Adiciona rotas de acesso à users
  game-slot/backend/app.js
  game-slot/backend/controllers/user.js
  game-slot/backend/middlewares/jwt.js
  game-slot/backend/models/User.js
  game-slot/backend/routes/auth.js
  game-slot/backend/routes/index.js
  game-slot/backend/routes/user.js
Labels: enhancement

#79 Adiciona rotas de follow/unfollow de usuários no back
  game-slot/backend/controllers/user.js
  game-slot/backend/models/User.js
  game-slot/backend/routes/user.js
Labels: enhancement

#84 Adiciona likes e note em Review
  game-slot/backend/controllers/review.js
  game-slot/backend/models/Review.js
  game-slot/backend/routes/review.js
  game-slot/backend/services/review.service.js
Labels: enhancement

#86 Implementa timeline
  game-slot/backend/controllers/review.js
  game-slot/backend/models/Review.js
  game-slot/backend/models/User.js
  game-slot/backend/routes/review.js
  game-slot/backend/services/review.service.js
Labels: enhancement

#88 Troca reviews para sistema de notas
  game-slot/frontend/src/constants/index.tsx
  game-slot/frontend/src/hooks/useGameReviews.ts
  game-slot/frontend/src/hooks/useReviewActions.ts
  game-slot/frontend/src/icons/Star.tsx
  game-slot/frontend/src/pages/GamePage/Reviews/GameReview.tsx
  game-slot/frontend/src/pages/GamePage/Reviews/ReviewForm.tsx
  game-slot/frontend/src/pages/UserPage/Reviews.tsx
  game-slot/frontend/src/typings/index.d.ts
Labels: rewriting

#91 Adiciona timeline
  game-slot/backend/services/review.service.js
  game-slot/frontend/src/components/GameReview.tsx
  game-slot/frontend/src/pages/GamePage/Reviews/index.tsx
  game-slot/frontend/src/pages/Home/Timeline.tsx
  game-slot/frontend/src/pages/Home/index.tsx
  game-slot/frontend/src/pages/UserList/CurrentUserLists.tsx
  game-slot/frontend/src/pages/UserList/UserList.tsx
  game-slot/frontend/src/pages/UserPage/Reviews.tsx
  game-slot/frontend/src/services/users.service.ts
Labels: enhancement
